<a href="https://colab.research.google.com/github/dhindakiflia/BigData/blob/main/naive_bayes.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Classification Naive Bayes

In [2]:
import pandas as pd
import numpy as np

In [21]:
df = pd.read_csv('../content/sample_data/bank.csv',delimiter=';')
df = df.replace({'y': {'yes': 0, 
                        'no': 1}})

In [22]:
df.head()

age          job  marital  education  ... pdays  previous poutcome  y
0   30   unemployed  married    primary  ...    -1         0  unknown  1
1   33     services  married  secondary  ...   339         4  failure  1
2   35   management   single   tertiary  ...   330         1  failure  1
3   30   management  married   tertiary  ...    -1         0  unknown  1
4   59  blue-collar  married  secondary  ...    -1         0  unknown  1

[5 rows x 17 columns]

In [23]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4521 entries, 0 to 4520
Data columns (total 17 columns):
 #   Column     Non-Null Count  Dtype 
---  ------     --------------  ----- 
 0   age        4521 non-null   int64 
 1   job        4521 non-null   object
 2   marital    4521 non-null   object
 3   education  4521 non-null   object
 4   default    4521 non-null   object
 5   balance    4521 non-null   int64 
 6   housing    4521 non-null   object
 7   loan       4521 non-null   object
 8   contact    4521 non-null   object
 9   day        4521 non-null   int64 
 10  month      4521 non-null   object
 11  duration   4521 non-null   int64 
 12  campaign   4521 non-null   int64 
 13  pdays      4521 non-null   int64 
 14  previous   4521 non-null   int64 
 15  poutcome   4521 non-null   object
 16  y          4521 non-null   int64 
dtypes: int64(8), object(9)
memory usage: 600.6+ KB


In [24]:
df.empty

False

In [34]:
x = df[['age','balance','day','day','duration','campaign','pdays','previous']]
x.head()

age  balance  day  day  duration  campaign  pdays  previous
0   30     1787   19   19        79         1     -1         0
1   33     4789   11   11       220         1    339         4
2   35     1350   16   16       185         1    330         1
3   30     1476    3    3       199         4     -1         0
4   59        0    5    5       226         1     -1         0

In [35]:
y = df['y']
y.head()

0    1
1    1
2    1
3    1
4    1
Name: y, dtype: int64

In [36]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state = 0)

In [37]:
# Import Gaussian Naive Bayes model
from sklearn.naive_bayes import GaussianNB

modelnb = GaussianNB()

nbtrain = modelnb.fit(x_train, y_train)
nbtrain.class_count_

array([ 409., 3207.])

In [38]:
y_pred = nbtrain.predict(x_test)
y_pred

array([1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1,
       1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1,
       1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1,
       0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1,
       1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1,
       0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0,

In [39]:
nbtrain.predict_proba(x_test)

array([[0.07877895, 0.92122105],
       [0.01734862, 0.98265138],
       [0.60259872, 0.39740128],
       ...,
       [0.05986142, 0.94013858],
       [0.57328404, 0.42671596],
       [0.17090171, 0.82909829]])

In [40]:
from sklearn.metrics import confusion_matrix

confusion_matrix(y_test, y_pred)

array([[ 47,  65],
       [ 81, 712]])

In [42]:
from sklearn.metrics import classification_report
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.37      0.42      0.39       112
           1       0.92      0.90      0.91       793

    accuracy                           0.84       905
   macro avg       0.64      0.66      0.65       905
weighted avg       0.85      0.84      0.84       905

